---
kind: pipeline
name: default

steps:
  - name: tests
    image: golang:1.13
    commands:
    - go build
    - go test -coverprofile coverage.html
---
kind: signature
hmac: 5880c971790c34a340b073608c6ffed8cb14509779038b5807060c68abd76073
